services:


#########################################################################################################################################
#       Application CLUB
#########################################################################################################################################


  back40club:
    container_name: back40club
    image: back40club:local
    restart: always
    environment:
      ConnectionStrings__Default: Server=*;Port=*;Database=*;User=*;Password=*
      Google__ClientId: *
      Jwt__Key: $${JWT_KEY:*}
      Jwt__Issuer: *
      Jwt__Audience: *
      VITE_GOOGLE_CLIENT_ID: *
    depends_on:
      - mariadb40club


  front40club:
    container_name: front40club
    image: front40club:local
    ports:
      - "85:80"
    restart: always
    environment:
      VITE_GOOGLE_CLIENT_ID: *
    depends_on:
      - back40club


  mariadb40club:
    container_name: mariadb40club
    image: mariadb:local
    environment:
      MYSQL_ROOT_PASSWORD: *
      MYSQL_DATABASE: *
      MYSQL_USER: *
      MYSQL_PASSWORD: *
    volumes:
      - db_data40club:/var/lib/mysql
    restart: always



volumes:
   db_data40club:
      driver: local
      driver_opts:
         type: none
         o: bind
         device: /opt/docker/data/mariadb40club
 #  proxy-config:
